version: '3.9'

services:
  backend:
    container_name: backend
    build: 
      context: ./server
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
    depends_on:
      - db

  frontend:
    container_name: frontend
    build: 
      context: ./client
    ports:
      - "3000:3000"

  db:
    image: postgres:17.2-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"